### ISSUE TITLE
Webpack 2 support needed

### ISSUE THREAD

**Issue by dschissler** [eoin/entry-loader#2]
I need this to work with Webpack 2 for PDF.js support.

**Comment by vseventer** [comment]
Just out of curiosity, what does not work exactly? I have been using entry-loader successfully, except for watch tasks, which I submitted a PR for in #1.

**Comment by jarkonik** [comment]
If it works, then i guess the peer dependency version requirement can be relaxed to include webpack versions > 2?

**Comment by eoin** [comment]
0.2.0 supports Webpack 2.x.
